### ISSUE TITLE
Local Management of SSC PoE switch

### ISSUE THREAD

**Issue by romiof** [slydiman/sscpoe#1]
Hello! This question is a little off topic, but I don't know where to ask. 

I bought at AliExpress a switch from this company, my model is a GPS208.

I realy liked the managent interface of this equipament, but I'm worried about becoming dependent of some chinese servers, to configure or monitoring my switch.
If someday they close his cloud / servers, the management interface is gone.

In your project, did you discovered how to monitoring and interact with this switch, using only local network / homelab, without SSC's cloud?

**Comment by hBrinkmann62** [comment]
Hi, another question: Would it be possible to enable / disable a port?

**Comment by slydiman** [comment]
No. But disabling POE must be enough. Do you use a POE compatible device with an external power?

It is possible to
- Enable/disable POE
- Enable/disable POE extend power
- View port status
- Set the rate limit per port

I'm not sure the limit 0 will work. And most probably devices will not recognize it correctly. So the behavior is undefined.

**Comment by slydiman** [comment]
It is possible to manage SSC POE switch locally using the app for Windows.
[PCsscV3202407092_EN_Windows_x64.zip](http://www.sscee.com/en/en/col.jsp?id=105)
Note you need 6 digits password for the device.

It uses broadcast UDP to 239.0.0.100 and BASE64 encoded packets with \r\n at the end.
I will try to decode the protocol and implement the local management.

**Comment by slydiman** [comment]
[Release 2024.08.28](https://github.com/slydiman/sscpoe/releases/tag/2024.08.28)
