### ISSUE TITLE
 Model SSC-GPS316

### ISSUE THREAD

**Issue by MDV85** [slydiman/sscpoe#4]
Hi.  I think to buy yours product .. and i have a question ..  Model SSC-GPS316 supports local management in Home Assistant  or not? Thanks!

**Comment by slydiman** [comment]
Hello.
This is `Unofficial` integration. It is not my product. I'm just an individual programmer.
I don't know about the SSC-GPS316 local management for sure. Hope yes. 
I have PS308G and GPS204. Both have the firmware v6.0.231024.
The behavior for all SSC managed POE switches v6.* looks the same.

**Comment by MDV85** [comment]
> Hello. This is `Unofficial` integration. It is not my product. I'm just an individual programmer. I don't know about the SSC-GPS316 local management for sure. Hope yes. I have PS308G and GPS204. Both have the firmware v6.0.231024. The behavior for all SSC managed POE switches v6.* looks the same.

Ооо) Спасибо! Попробую заказать тогда.. Спасибо за работу!
