### ISSUE TITLE
[GPS208] Reverse port numbers 

### ISSUE THREAD

**Issue by JanickGers85** [slydiman/sscpoe#5]
First of all thanks for your work: when I saw that local management has been implemented I was very happy 😁
Integration works well, but I've noticed that port number are wrong with GPS208: port 8 on the integration is port 1 on the switch, port 7 is port 2 and so on.

Here what the integration shows
![Screenshot_2024-09-07-11-43-46-672_io homeassistant companion android~2](https://github.com/user-attachments/assets/545c1ef6-ecac-4fda-8fff-bbb96161ac74)
And here what the app shows
![Screenshot_2024-09-07-11-43-38-238_com sscee app sscpoe](https://github.com/user-attachments/assets/eba5a57c-2585-450e-80f4-e5ad86d4e476)
As you can see by the power consumption ports are shown in reverse.

Device information from the app
![Screenshot_2024-09-07-13-22-19-798-edit_com sscee app sscpoe](https://github.com/user-attachments/assets/b64ef419-ab2d-4f0f-a165-94a43c5a94e3)

**Comment by slydiman** [comment]
I don't have GPS208. But GPS204 has the reverse ports order too. PS308G has the correct order. 
Probably all devices GPS*** serie have the reverse order and all devices PS***G serie have the correct order.
I will try to reverse the order in next release for GPS*** devices. Thanks

**Comment by slydiman** [comment]
Please try the new version 2024.09.07.

**Comment by JanickGers85** [comment]
Works perfectly, thanks very much for your work, really appreciated!
