### ISSUE TITLE
port numbers mismatch with 16port poe switch (GPS316 v6)

### ISSUE THREAD

**Issue by numminorih-git** [slydiman/sscpoe#6]
Hi,

faced with port mismatch (local control):

Port - Soft (addon) / fact (named on front of device)

port - 16 / 1
port - 15 / 2
port - 14 / 3
port - 13 / 4
port - 12 / 5
port - 11 / 6
port - 10 / 7
port - 9 / 8
port - 8 / 9
port - 7 / 10
port - 6 / 11
port - 5 / 12
port - 4 / 13
port - 3 / 14
port - 2 / 15
port - 1 / 16

**Comment by numminorih-git** [comment]
And one more issue:

After power off/on (in HA entity go to offline) Integration requires reconfiguration and doesn't accept standard password.  Help only totally delete device and add again.

**Comment by numminorih-git** [comment]
1st issue fixed by specify in custom_components/sscpoe/coordinator.py  in 39 line return sn.startswith("GPS") to return sn.startswith("GPS1") as for gps1xxx need revert naming (as I know).

**Comment by slydiman** [comment]
GPS208 and GPS204 require the port reverse.
PS308G has the correct order.
I assumed that all devices GPS*** serie have the reverse order and all devices PS***G serie have the correct order.
It seems GPS316 doesn't follow this logic.
Probably 2** series require the port reverse.
I will update the logic.

To investigate the second issue I need logs.
Please do the following:
- activate the debug logging in the integration settings,
- power off/on the device, 
- wait for 1 min, 
- try to reconfigure.
- collect and provide logs.

Probably something is wrong around local login/activate logic.

**Comment by numminorih-git** [comment]
only one that I find:

Logger: custom_components.sscpoe
Source: helpers/update_coordinator.py:407
integration: SSCPOE ([documentation](https://github.com/slydiman/sscpoe), [issues](https://github.com/slydiman/sscpoe/issues))
First occurred: 23:10:03 (1 occurrences)
Last logged: 23:10:03

Authentication failed while fetching sscpoe data: Please conduct security verification first

**Comment by numminorih-git** [comment]
Here:
'mac': 'E04machided' and GPS316numbershided - changed.
[log.txt](https://github.com/user-attachments/files/17176192/log.txt)

**Comment by numminorih-git** [comment]
one more thing, do you investigate for achieve sensors with tx/rx and port speed?
Thx

**Comment by numminorih-git** [comment]
> What is the source of this knowledge?

2 of gps1xx with v2 software and 3 with v5  - has reverse port naming as GPS2x8 with v4 and some others...

**Comment by slydiman** [comment]
> 2 of gps1xx with v2 software and 3 with v5 - has reverse port naming as GPS2x8 with v4 and some others...

Wow. Would you provide the full list of known models and describe which have the reverse ports, please?

**Comment by slydiman** [comment]
> Here it is: ... log.txt

This log does not contain any login/activation errors or requests. 
I see `SSCPOE_local_request(detail, GPS316*): timeout` at the beginning and then all request are successful.
Can you still reproduce the issue?

**Comment by numminorih-git** [comment]
> This log does not contain any login/activation errors or requests.
> I see `SSCPOE_local_request(detail, GPS316*): timeout` at the beginning and then all request are successful.
> Can you still reproduce the issue?

yes, still here, it's only one that I have. 

"and then all request are successful." - its after i delete and readd it.

**Comment by numminorih-git** [comment]
> > 2 of gps1xx with v2 software and 3 with v5 - has reverse port naming as GPS2x8 with v4 and some others...
> 
> Wow. Would you provide the full list of known models and describe which have the reverse ports, please?

this is the full list)

**Comment by numminorih-git** [comment]
> > one more thing, did you investigate for achieve sensors with tx/rx and port speed?
> 
> Sure. I will add these sensors, but they will be deactivated by default.

Ouh, super, will wait. 

just thoughts:
It seems to me that we need to remove the renaming of ports to the format "Port 1 POE" from "GPSxxx", since this name is not displayed anywhere except in the addon itself and when adding sensors to the dashboard it causes slight confusion.

**Comment by slydiman** [comment]
> "and then all request are successful." - its after i delete and readd it.

This log is useless. I need the log during the issue occurred and when you tried to reconfigure the device.
Note you can enable the debug log for this integration in `configuration.yaml` file even if this integration is not added to Home Assistant or all sscpoe devices are removed:
```
logger:
  default: info
  logs:
    custom_components.sscpoe: debug
```

**Comment by slydiman** [comment]
Try the new version [2024.09.30](https://github.com/slydiman/sscpoe/releases/tag/2024.09.30).

**Comment by numminorih-git** [comment]
UPD with 2024.11.11

1. port naming - correct
2. after switch reboot HomeAssistant still need to reconfigure addon but without delete. Jus use password "123456".

Please advise, what can i do to "autoadd" switch after power loss without reconf. with password .

THX!

**Comment by slydiman** [comment]
I will try to add auto reconfig with the default password in the next release.

**Comment by slydiman** [comment]
https://github.com/slydiman/sscpoe/releases/tag/2024.12.02

**Comment by numminorih-git** [comment]
> https://github.com/slydiman/sscpoe/releases/tag/2024.12.02

yes, it works now.
THX
