### ISSUE TITLE
Not able to logon over the integration

### ISSUE THREAD

**Issue by MiAutomations** [slydiman/sscpoe#8]
Hello I'm able to logon with the same credentials on the APP but now I'm facing this issue when I try to perform the logon on the integration use the same credentials ...

Can you please help me in order to solve this issue? 

![image](https://github.com/user-attachments/assets/39cef0ca-7302-4560-a8e2-8682f14ac711)

Thank you

**Comment by MiAutomations** [comment]
Solved the issue is related to the caps letters 

Thank you

**Comment by slydiman** [comment]
Please note the following from the description page:

> Note: The cloud server does not support multiple connections to the same account from Home Assistant and the SSCPOE app. If you are using the cloud management, the device in Home Assistant will disappear after connecting from the official SSCPOE app and will be reconnected within 30 seconds automatically. You can share the project in the official SSCPOE app to other account and use this account for this integration. The device settings in the SSCPOE app are available only for the admin account.
