### ISSUE TITLE
Can't login in local mode

### ISSUE THREAD

**Issue by baradetsky** [slydiman/sscpoe#9]
Password incorrect, but its default
![2024-12-14_22-39-31](https://github.com/user-attachments/assets/cb3de040-e81c-481b-a6cc-a9dd757d8eb9)

**Comment by slydiman** [comment]
Be sure you can login locally using [Windows desktop config app](http://www.sscee.com/en/en/col.jsp?id=105).

The activation code may be changed in the official SSCPOE app (on Android/iPhone). Try to reset it to 123456.
